# Generated by Django 4.0.6 on 2022-09-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('planId', models.CharField(max_length=50)),
                ('bplInventoryItemId', models.IntegerField()),
                ('billPlanName', models.CharField(default='', max_length=50)),
                ('freebieCount', models.IntegerField(default=0)),
                ('pricePoint', models.IntegerField(max_length=300)),
                ('billPlanCategory', models.CharField(max_length=50)),
                ('planComponents', models.JSONField()),
            ],
        ),
    ]
