# Generated by Django 4.1.1 on 2022-09-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='pricePoint',
            field=models.IntegerField(),
        ),
    ]
